### ISSUE TITLE
Add a link to the code from dashboard

### ISSUE THREAD

**Issue by scottveirs** [liu-zoe/orcasalmon#1]
As a developer or data scientist viewing the dashboard, 
I would like a link to the Github repository where the open source code is accessible and documented, 
so that I can understand more deeply how the data are acquired, analyzed, and visualized.

**Proposed solution:**
Once dashboard is through alpha-testing and code is open sourced in a location that is intended to be permanent (e.g. Orcasound or Salish-Sea organization on Github), add a "Github" link or button to the dashboard (maybe in the upper right by the Orcasound logo, or in the empty space in the lower right corner?) 

Here's how Pete did it within the Acartia web app:
<img width="1024" alt="Screenshot 2023-04-11 at 9 19 27 AM" src="https://user-images.githubusercontent.com/14044595/231226223-5646ddb9-58bb-4211-8b3a-6c05c6276ff7.png">

**Comment by liu-zoe** [comment]
Great idea! Will add this to my to-do list.

**Comment by liu-zoe** [comment]
Added a GitHub icon with link to the current repo in the upper right corner next to the "orcasound" logo. I'll keep this issue open so I remember to update the link after we fork the repo to its permanent location.

**Comment by liu-zoe** [comment]
Repo forked to https://github.com/salish-sea.
