### ISSUE TITLE
Enhancement idea: intermittently publish the fish data in accessible format(s)

### ISSUE THREAD

**Issue by scottveirs** [liu-zoe/orcasalmon#2]
Rather than having others re-use your scraping code to gather salmon data, 
maybe publish a `.csv` or other convenient format in your repo or a new one in the `salish-sea` organization, 
so that others can just ingest directly?

**Comment by scottveirs** [comment]
I just noticed that the new paper by [Stewart et al., 2023](https://onlinelibrary.wiley.com/doi/10.1111/mms.13012), used siloed data and didn't provide it for reproducibility, but did include a distillation of Albion data in tabular form. Perhaps it's of interest (e.g. to error-check your scraping script?), but mostly I wanted to highlight it as a non-optimal way of addressing this issue. (Copy/pasting a table from a PDF is annoying when you could have provided an actual data table for programatic convenience as a digital supplement.)

<img width="691" alt="Screenshot 2023-04-11 at 11 45 14 AM" src="https://user-images.githubusercontent.com/14044595/231260929-7450fc62-1a0c-45fe-add4-d0280ab8c3ac.png">

**Comment by liu-zoe** [comment]
The scrapped data are stored as csv files in the data folder and are organized by sources. When the repo gets forked to sealish-sea, we can set up GitHub action to continue automatically saving the scrapped data to files.

**Comment by scottveirs** [comment]
@zoe I know you've closed this issue, but I just saw in the Ettinger paper that they published their Albion data in a [SRKW phenology Github repo](https://github.com/AileneKane/srkwphen)... 

<img width="404" alt="Screenshot 2023-04-12 at 9 47 35 PM" src="https://user-images.githubusercontent.com/14044595/231656300-20b0081a-cb3f-414c-bc3f-ac2e54ea546d.png">

...but I don't see the Orcamaster + Lime Kiln longitudinal presence/absence data for SRKWs that they said would be there...

<img width="700" alt="Screenshot 2023-04-12 at 9 45 44 PM" src="https://user-images.githubusercontent.com/14044595/231655893-3515edd0-e8b3-46e5-8e68-63d413bd4c88.png">

Am I missing something @AileneKane ?

At any rate, Zoe, I continue to take notes on possible additional sources of salmon data in this [Acartia Project card related to SRKW-salmon integrations](https://github.com/orgs/salish-sea/projects/1?pane=issue&itemId=19450403), including the WDFW escapement data that Ailene scraped and provided as a .csv file it seems.

**Comment by liu-zoe** [comment]
<img width="1023" alt="Screenshot 2023-04-13 at 2 04 22 PM" src="https://user-images.githubusercontent.com/7928761/231858459-d2d6d523-6951-47fe-bdca-6b52e92858a1.png">
I took a quick look at orcaphen_esr2022.R in Ailene's repo, and it seems that Lime Kilm subset data was read from data/limedat.csv. The file is not currently included in the repo. My guess is that there may be some limitations to where the Orca Master data can be released... Ailene would probably be able to answer this better.

**Comment by AileneKane** [comment]
Thank you for pointing this out- I will take a look and add the data file. I was waiting to recieve the appropriate permissions from orcamaater.Sent from my iPhoneOn Apr 13, 2023, at 1:15 PM, Zoe Liu ***@***.***> wrote:﻿

I took a quick look at orcaphen_esr2022.R in Ailene's repo, and it seems that Lime Kilm subset data was read from data/limedat.csv. The file is not currently included in the repo. My guess is that there may be some limitations to where the Orca Master data can be released... Ailene would probably be able to answer this better.

**Comment by scottveirs** [comment]
Thanks, @AileneKane ! And no rush... 

We appreciate your excellent publication and use of Github to help lead folks towards more reproducible science.

@liu-zoe you right about Bob Otis longitudinal dataset from Lime Kiln.

The SRKW occurrence data are referenced in 
 [fitsrkwmods_regional.R](https://github.com/AileneKane/srkwphen/blob/main/analyses/fitsrkwmods_regional.R) and look like:

```
j_dat_assumeSRKW.csv
k_dat_assumeSRKW.csv
l_dat_assumeSRKW.csv
```
but the methods section suggests there was a processing to obtain this "subset of Orca Master" so the entire procedure may not be reproducible?
