### ISSUE TITLE
Display latest year of Chinook data on top

### ISSUE THREAD

**Issue by scottveirs** [liu-zoe/orcasalmon#3]
I find myself checking the dashboard to see what's currently happening with this year's counts... but to see the (mostly near-zero so far) data points for 2023 I have to uncheck 2021 and 2022. Here's two screenshots illustrating the issue:

The default view when dashboard is first loaded for Bonneville data:

<img width="788" alt="Screenshot 2023-04-11 at 9 12 06 AM" src="https://user-images.githubusercontent.com/14044595/231227483-730814f6-7ca3-4ec4-9fca-422feddbc358.png">

Notice how the majority of 2023 data points are covered by data points from previous years.

The view I find most helpful for quickly "seeing" the condition of current Chinook returns on the Columbia relative to the historic mean:

<img width="790" alt="Screenshot 2023-04-11 at 9 11 51 AM" src="https://user-images.githubusercontent.com/14044595/231227488-5b9c442e-4498-48a4-8cf1-dd8937ee7270.png">

**Proposed solution:**
Invert the plot order (and display in the legend, presumably) from:

1. 2023
2. 2022
3. 2021
4. historic

to

1. 2021
2. 2022
3. 2023
5. historic

**Comment by liu-zoe** [comment]
Years reordered!
