### ISSUE TITLE
Minor edits for Data sources in Orca Map view

### ISSUE THREAD

**Issue by scottveirs** [liu-zoe/orcasalmon#4]
Hey @liu-zoe , noticed these three (minor) issues with the text at the bottom of the Orca Map view: 

<img width="943" alt="Screenshot 2023-04-14 at 10 32 07 AM" src="https://user-images.githubusercontent.com/14044595/232116502-9e998748-2cd6-423f-8e7c-bd71e0f4e3fb.png">

1. Since the word "data" is plural, the Source 1 text could read something like: `Orca data sources are retrieved from Acartia.`
2. In the Source 2 text, the work "talk" occurs twice.
3. At least on OSX+Chrome the map is overlaying the "Data source" title, slightly (but it's still readable).

**Comment by liu-zoe** [comment]
Nice catch! The overlapping of text and map is fixed. Typos are corrected.
