### ISSUE TITLE
Make default initial view of time series Albion v Bonneville

### ISSUE THREAD

**Issue by scottveirs** [liu-zoe/orcasalmon#5]
With the nice new map showing both locations, I wonder if it would be more intuitive to have the initial view of the time series contain both Albion and Bonneville, rather than the current default (just Albion):

<img width="1736" alt="Screenshot 2023-05-22 at 1 41 15 PM" src="https://github.com/liu-zoe/orcasalmon/assets/14044595/f06018dc-dc25-48fb-b5c7-e8702f59cde1">

If implemented, the initial view of the app might look more like this:

<img width="1739" alt="Screenshot 2023-05-22 at 1 40 58 PM" src="https://github.com/liu-zoe/orcasalmon/assets/14044595/1b3e37da-9c02-4001-8180-f5bca8e1af7d">

By the way, the peak Bonneville levels recently are way above the mean!

One thing I like about the suggested new default view is that it really poses the question; what happened to the spring Fraser Chinook? Yet again the the Albion 2023 values seem to have flatlined relative to the historic mean!!

**Comment by scottveirs** [comment]
Also, @liu-zoe -- I just noticed that on the new map the `Bonneville` label is missing an `l` ...

**Comment by liu-zoe** [comment]
I can definitely switch the default view to Bonneville + Abion. Will do that later this week and have it staged for next week's deployment. Good catch of the typo in the static map. I'll reach out to Lingmei and ask her to correct it.

**Comment by scottveirs** [comment]
Default view looks great and is proving useful during Orcasound's weekly standups!

BTW the static map is throwing a 404...

**Comment by liu-zoe** [comment]
There is a typo in the static map file name in app.py and it is now fixed.
