### ISSUE TITLE
Individual Pods Aren't Shown on Maps for 2022 & 2023

### ISSUE THREAD

**Issue by Cetacean-Communication** [liu-zoe/orcasalmon#6]
When selecting an individual pod for the years 2022 or 2023, only "All Pods" data points are shown on the map. The individual pod data are shown in the timeline, but not on the map. The individual pods data are shown separately for 2021 and older years. It's just the 2022 and 2023 years that have the issue.

**Comment by liu-zoe** [comment]
Should be fixed now!
